opam-version: "2.0"
name: "CompCert-Ce"
version: "3.16-dev.20250728ce"
synopsis: "The CompCert C compiler (rv32-linux)"
maintainer: "Michael Soegtrop and Xavier Leroy"
authors: "Xavier Leroy <xavier.leroy@college-de-france.fr>"
license: "INRIA Non-Commercial License Agreement"
tags: [
  "category:Computer Science/Semantics and Compilation/Compilation"
  "category:Computer Science/Semantics and Compilation/Semantics"
  "keyword:C"
  "keyword:compiler"
  "logpath:compcert"
  "date:2025-07-04"
]
homepage: "https://compcert.org/"
bug-reports: "https://github.com/fajb/CompCert/tree/ClightCe"
depends: [
  "coq" {>= "8.13.0" & < "8.21~"}
  "menhir" {>= "20200624" & != "dev"}
  "ocaml" {>= "4.05.0" & < "5~"}
  "coq-flocq" {>= "4.1.0" & < "5~"}
  "coq-menhirlib" {>= "20200624"}
]
build: [
  [
    "./configure"
    "rv32-linux"
    "-toolprefix"
    "riscv64-unknown-elf-"
    "-prefix"
    "%{prefix}%"
    "-install-coqdev"
    "-clightgen"
    "-use-external-Flocq"
    "-use-external-MenhirLib"
    "-coqdevdir"
    "%{lib}%/coq/user-contrib/compcert"
    "-ignore-coq-version"
  ]
  [make "-j%{jobs}%" {ocaml:version >= "4.06"}]
]
install: [make "install"]
dev-repo: "git+https://gitlab.inria.fr/cchavano/compcert-ce.git"
