opam-version: "2.0"
name: "CompCert-Ce"
version: "3.17-20260508ce"
synopsis: "The CompCert C compiler for Barocq (64 bit)"
maintainer: "Michael Soegtrop and Xavier Leroy"
authors: "Xavier Leroy <xavier.leroy@college-de-france.fr>"
license: "INRIA Non-Commercial License Agreement"
homepage: "https://gitlab.inria.fr/cchavano/compcert-ce"
bug-reports: "https://gitlab.inria.fr/cchavano/compcert-ce/-/issues"
depends: [
  "coq" {>= "8.15.0" & < "9.2~"}
  "menhir" {>= "20200624" & != "20260122" & != "dev"}
  "ocaml" {>= "4.05.0" & < "5~"}
  "coq-flocq" {>= "4.1.0" & < "5~"}
  "coq-menhirlib" {>= "20200624"}

]
conflicts: ["coq-compcert"]
build: [
  [
    "./configure"
    "rv64-linux"
    "-toolprefix"
    "riscv64-unknown-elf-"
    "-prefix"
    "%{prefix}%"
    "-install-coqdev"
    "-clightgen"
    "-use-external-Flocq"
    "-use-external-MenhirLib"
    "-coqdevdir"
    "%{lib}%/coq/user-contrib/compcert"
    "-ignore-coq-version"
  ]
  [make "-j%{jobs}%" {ocaml:version >= "4.06"}]
]
install: [make "install"]
dev-repo: "git+https://gitlab.inria.fr/cchavano/compcert-ce.git"
